import { motion } from "framer-motion";
import {
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  Radar,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Cell,
  ResponsiveContainer,
  Tooltip,
} from "recharts";
import { Download, AlertTriangle, AlertCircle, Info, CheckCircle, RotateCcw } from "lucide-react";
import { jsPDF } from "jspdf";

interface TopicCoverage {
  topic: string;
  score: number;
  severity: "critical" | "high" | "medium" | "low";
  recommendation: string;
}

interface AuditResult {
  overallScore: number;
  topicCoverages: TopicCoverage[];
  summary: string;
}

interface GapReportProps {
  result: AuditResult;
  kbName: string;
  onReset: () => void;
}

const severityConfig = {
  critical: { color: "text-red-400", bg: "bg-red-400/10", border: "border-red-400/30", icon: AlertTriangle, label: "Critical" },
  high: { color: "text-orange-400", bg: "bg-orange-400/10", border: "border-orange-400/30", icon: AlertCircle, label: "High" },
  medium: { color: "text-yellow-400", bg: "bg-yellow-400/10", border: "border-yellow-400/30", icon: Info, label: "Medium" },
  low: { color: "text-green-400", bg: "bg-green-400/10", border: "border-green-400/30", icon: CheckCircle, label: "Low" },
};

function getScoreColor(score: number): string {
  if (score >= 70) return "text-green-400";
  if (score >= 40) return "text-yellow-400";
  return "text-red-400";
}

function getScoreRing(score: number): string {
  if (score >= 70) return "border-green-400/40";
  if (score >= 40) return "border-yellow-400/40";
  return "border-red-400/40";
}

export function GapReport({ result, kbName, onReset }: GapReportProps) {
  const radarData = result.topicCoverages.map((tc) => ({
    topic: tc.topic.length > 20 ? tc.topic.slice(0, 18) + "..." : tc.topic,
    fullTopic: tc.topic,
    coverage: Math.round(tc.score * 100),
  }));

  const gaps = result.topicCoverages.filter((tc) => tc.severity !== "low");

  const exportPDF = () => {
    const doc = new jsPDF();
    const margin = 20;
    let y = margin;

    doc.setFontSize(22);
    doc.setTextColor(0, 200, 160);
    doc.text("DocAudit Gap Report", margin, y);
    y += 12;

    doc.setFontSize(12);
    doc.setTextColor(150, 150, 150);
    doc.text(`Knowledge Base: ${kbName}`, margin, y);
    y += 8;
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, y);
    y += 12;

    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    doc.text(`Overall Coverage Score: ${result.overallScore}%`, margin, y);
    y += 10;

    doc.setFontSize(10);
    doc.setTextColor(180, 180, 180);
    const summaryLines = doc.splitTextToSize(result.summary, 170);
    doc.text(summaryLines, margin, y);
    y += summaryLines.length * 5 + 10;

    doc.setFontSize(14);
    doc.setTextColor(255, 255, 255);
    doc.text("Topic Coverage Details", margin, y);
    y += 10;

    for (const tc of result.topicCoverages) {
      if (y > 270) {
        doc.addPage();
        y = margin;
      }

      doc.setFontSize(11);
      const sevColor =
        tc.severity === "critical" ? [239, 68, 68] :
        tc.severity === "high" ? [251, 146, 60] :
        tc.severity === "medium" ? [250, 204, 21] :
        [74, 222, 128];
      doc.setTextColor(sevColor[0], sevColor[1], sevColor[2]);
      doc.text(`[${tc.severity.toUpperCase()}]`, margin, y);

      doc.setTextColor(255, 255, 255);
      doc.text(`${tc.topic} — ${Math.round(tc.score * 100)}%`, margin + 25, y);
      y += 6;

      doc.setFontSize(9);
      doc.setTextColor(160, 160, 160);
      const recLines = doc.splitTextToSize(tc.recommendation, 155);
      doc.text(recLines, margin + 5, y);
      y += recLines.length * 4 + 6;
    }

    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by DocAudit — Synaptica Knowledge Systems", margin, 285);

    doc.save(`docaudit-report-${kbName.replace(/\s+/g, "-").toLowerCase()}.pdf`);
  };

  interface TooltipPayloadEntry {
    value: number;
    payload: { fullTopic: string; coverage: number };
  }

  interface CustomTooltipProps {
    active?: boolean;
    payload?: TooltipPayloadEntry[];
  }

  const CustomTooltip = ({ active, payload }: CustomTooltipProps) => {
    if (active && payload && payload.length) {
      return (
        <div className="glass rounded-lg px-3 py-2 text-sm">
          <p className="text-foreground font-medium">{payload[0].payload.fullTopic}</p>
          <p className="text-primary">{payload[0].value}% coverage</p>
        </div>
      );
    }
    return null;
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-8"
    >
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-foreground">Gap Analysis Report</h2>
          <p className="text-muted-foreground">{kbName}</p>
        </div>
        <div className="flex gap-3">
          <button onClick={onReset} className="btn-secondary flex items-center gap-2 text-sm !py-2 !px-4">
            <RotateCcw className="w-4 h-4" />
            New Audit
          </button>
          <button onClick={exportPDF} className="btn-primary flex items-center gap-2 text-sm !py-2 !px-4">
            <Download className="w-4 h-4" />
            Export PDF
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="glass rounded-2xl p-6 flex flex-col items-center justify-center text-center">
          <div className={`w-24 h-24 rounded-full border-4 ${getScoreRing(result.overallScore)} flex items-center justify-center mb-3`}>
            <span className={`text-3xl font-bold ${getScoreColor(result.overallScore)}`}>
              {result.overallScore}
            </span>
          </div>
          <p className="text-sm text-muted-foreground">Overall Coverage Score</p>
        </div>

        <div className="glass rounded-2xl p-4 flex flex-col items-center justify-center">
          <div className="grid grid-cols-2 gap-3 w-full">
            {(["critical", "high", "medium", "low"] as const).map((sev) => {
              const count = result.topicCoverages.filter((t) => t.severity === sev).length;
              const config = severityConfig[sev];
              return (
                <div key={sev} className={`${config.bg} border ${config.border} rounded-xl px-3 py-2 text-center`}>
                  <p className={`text-lg font-bold ${config.color}`}>{count}</p>
                  <p className="text-xs text-muted-foreground">{config.label}</p>
                </div>
              );
            })}
          </div>
        </div>

        <div className="glass rounded-2xl p-4 flex items-center justify-center">
          <p className="text-sm text-muted-foreground leading-relaxed">{result.summary}</p>
        </div>
      </div>

      <div className="glass rounded-2xl p-6">
        <h3 className="text-lg font-semibold text-foreground mb-4">Coverage Map</h3>
        {radarData.length <= 12 ? (
          <ResponsiveContainer width="100%" height={350}>
            <RadarChart data={radarData}>
              <PolarGrid stroke="rgba(255,255,255,0.1)" />
              <PolarAngleAxis dataKey="topic" tick={{ fill: "rgba(255,255,255,0.6)", fontSize: 11 }} />
              <PolarRadiusAxis angle={30} domain={[0, 100]} tick={{ fill: "rgba(255,255,255,0.4)", fontSize: 10 }} />
              <Tooltip content={<CustomTooltip />} />
              <Radar
                name="Coverage"
                dataKey="coverage"
                stroke="hsl(165, 100%, 39%)"
                fill="hsl(165, 100%, 39%)"
                fillOpacity={0.2}
                strokeWidth={2}
              />
            </RadarChart>
          </ResponsiveContainer>
        ) : (
          <ResponsiveContainer width="100%" height={Math.max(350, radarData.length * 36)}>
            <BarChart data={radarData} layout="vertical" margin={{ left: 20, right: 20 }}>
              <XAxis type="number" domain={[0, 100]} tick={{ fill: "rgba(255,255,255,0.4)", fontSize: 10 }} />
              <YAxis type="category" dataKey="topic" width={160} tick={{ fill: "rgba(255,255,255,0.6)", fontSize: 11 }} />
              <Tooltip content={<CustomTooltip />} />
              <Bar dataKey="coverage" radius={[0, 4, 4, 0]}>
                {radarData.map((entry, index) => (
                  <Cell
                    key={`cell-${index}`}
                    fill={
                      entry.coverage >= 70 ? "rgb(74, 222, 128)" :
                      entry.coverage >= 40 ? "rgb(250, 204, 21)" :
                      "rgb(239, 68, 68)"
                    }
                    fillOpacity={0.7}
                  />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        )}
      </div>

      <div className="space-y-4">
        <h3 className="text-lg font-semibold text-foreground">
          {gaps.length > 0 ? `Prioritized Gaps (${gaps.length})` : "All Topics Covered"}
        </h3>

        {result.topicCoverages.map((tc, idx) => {
          const config = severityConfig[tc.severity];
          const Icon = config.icon;

          return (
            <motion.div
              key={tc.topic}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: idx * 0.05 }}
              className="glass rounded-xl p-5"
            >
              <div className="flex items-start gap-4">
                <div className={`w-9 h-9 rounded-lg ${config.bg} border ${config.border} flex items-center justify-center flex-shrink-0 mt-0.5`}>
                  <Icon className={`w-4 h-4 ${config.color}`} />
                </div>

                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-3 mb-2 flex-wrap">
                    <h4 className="font-semibold text-foreground">{tc.topic}</h4>
                    <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${config.bg} ${config.color} border ${config.border}`}>
                      {config.label}
                    </span>
                    <span className="text-sm text-muted-foreground ml-auto">
                      {Math.round(tc.score * 100)}%
                    </span>
                  </div>

                  <div className="w-full bg-white/5 rounded-full h-1.5 mb-3">
                    <div
                      className="h-1.5 rounded-full transition-all duration-500"
                      style={{
                        width: `${Math.round(tc.score * 100)}%`,
                        backgroundColor:
                          tc.severity === "critical" ? "rgb(239, 68, 68)" :
                          tc.severity === "high" ? "rgb(251, 146, 60)" :
                          tc.severity === "medium" ? "rgb(250, 204, 21)" :
                          "rgb(74, 222, 128)",
                      }}
                    />
                  </div>

                  <p className="text-sm text-muted-foreground leading-relaxed">{tc.recommendation}</p>
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>
    </motion.div>
  );
}
